### ISSUE TITLE
ci: push Docker images only after tests succeed

### ISSUE THREAD

**Issue by anuragxxd** [elixir-cloud-aai/foca#126]
CI pipeline from the Github Actions right now is running two jobs in parallel: 
- Docker: builds Docker images and pushes to the registry
- Linting and unit tests: lints code and runs unit and integration tests

A better approach will be to run the "Docker" job only after the "Linting and unit tests" job completed successfully.

Advantages of this will be:
- Bad code won't be pushed to the image registry
- It will save resources in case of failure

**Comment by uniqueg** [comment]
Closed by #127
