### ISSUE TITLE
Add support for mypy in the CI CD pipeline

### ISSUE THREAD

**Issue by kushagra189** [elixir-cloud-aai/foca#141]
Currently priority will be running `mypy` and fix code smells. Blocked by #140

**Comment by uniqueg** [comment]
I think this should be addressed along with #140 in the same PR. After all it's just a matter of adding `mypy` to `requirements_dev.txt` and copy/pasting the following lines into the CI config:

```
      - name: mypy
        run: mypy foca
```

**Comment by kushagra189** [comment]
Closing this issue.
