### ISSUE TITLE
bug: unable to provide custom model config for access control

### ISSUE THREAD

**Issue by alohamora** [elixir-cloud-aai/foca#181]
I am unable to provide a custom model config to foca because there is a condition in foca to only read the custom model config if API specs for access control APIs is  provided.
https://github.com/elixir-cloud-aai/foca/blob/d4c1280ccd93ce2849a2d0b0b35e609e93776ebd/foca/security/access_control/register_access_control.py#L108-L114

So, if I just want to provide a custom model config without providing a custom set of permission APIs, I am unable to do so.

**Comment by uniqueg** [comment]
Thanks for reporting 👍

Do you wanna fix it? :)
