### ISSUE TITLE
[Blocker] Potential dependencies issues to be caused due to flask-authz usage.

### ISSUE THREAD

**Issue by kushagra189** [elixir-cloud-aai/foca#184]
Tracking this concern here - https://github.com/pycasbin/flask-authz/issues/49

We might need to develop/maintain a similar logic in case `flask-authz` does not provide us bumps for latest approved versions.

**Comment by uniqueg** [comment]
Seems there is a fix now

**Comment by uniqueg** [comment]
I will close this unless. We can reopen if this really becomes an issue.
