### ISSUE TITLE
fix: `foca` attribute in `config`

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/foca#201]
# Description
`config` doesn't seem to have `foca` as an attribute. Came across this while going through [this](https://github.com/elixir-cloud-aai/proWES/blob/25f0e593c956fcd450f0f112c06c62ac768c77fe/pro_wes/app.py#L32) code snippet.

**Comment by uniqueg** [comment]
This is basically a duplicate of #144
