### ISSUE TITLE
docs: API docs broken

### ISSUE THREAD

**Issue by sivangbagri** [elixir-cloud-aai/foca#207]
**There are many instances where FOCA docs content is not populating under the headings.**

Refer :  https://foca.readthedocs.io/en/latest/modules/foca.api.html
<img width="557" alt="image" src="https://github.com/elixir-cloud-aai/foca/assets/61118650/da577f6f-c0af-47f4-b746-9e89581531bc">

**Comment by uniqueg** [comment]
Thanks for reporting @sivangbagri. Anyone interested to check why this is happening (and potentially fix)? Might require RTD credentials though, so pls let me know if I need to check myself.

**Comment by sivangbagri** [comment]
@uniqueg Hii ! I dont think anyone has shown interest in checking this,  could you please take a look
