### ISSUE TITLE
Solution for adding app_config.py and app_config.yaml to config

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-cloud-aai/foca#28]
Since the app_config.py and app_config.yaml can be different for different services, we need some solution to add those files to foca archetype.

Based on some discussions, the following different mechanism  has been proposed so as not to break anything with existing deployments:

1. check if WES_CONFIG is defined; if so, use that
2. check if the app's config directory contains an app_config.yaml file; if so, use that
3. otherwise use FOCA's default app_config.yaml

Note: WES_CONFIG is just specific to cwl-WES.

(1) and (3) are already in place. We need to figure out a solution for (2), which doesn't break any existing deployments.

See app_config.* files in these locations fore reference:
 
https://github.com/elixir-cloud-aai/cwl-WES/tree/dev/cwl_wes/config
https://github.com/elixir-cloud-aai/proWES/tree/dev/pro_wes/config
https://github.com/elixir-cloud-aai/proTES/tree/dev/pro_tes/config

**Comment by uniqueg** [comment]
This is basically superseded by #43 and #42. FOCA should not have its own `app_config.yaml`, but rather the new config class can take defaults for required params, where possible (probably in pretty much all cases). How the app developer gets the config YAML file to `FOCA()`, either as a file path or via en env variable is up to them.
