### ISSUE TITLE
Add decorator for protecting endpoints

### ISSUE THREAD

**Issue by kushagra189** [elixir-cloud-aai/foca#29]
We need to take into consideration and remove the following redundant code by adding a corresponding module to the Foca python package.
- https://github.com/elixir-cloud-aai/cwl-WES/blob/dev/cwl_wes/security/decorators.py
- https://github.com/elixir-cloud-aai/proWES/blob/dev/pro_wes/security/decorators.py

While addressing the same we need to keep in mind the following aspects
- check for the required parameters that are essential to pass through the decorator
- for unit tests relying on service/HTTP calls to identity provider, mock up responses in cases where valid token requirement is essential for the code to proceed.

**Comment by sarthakgupta072** [comment]
This is a duplicate of https://github.com/elixir-cloud-aai/foca/issues/25, right?
If yes, you can add the above content as a comment there.
