### ISSUE TITLE
Add factories module(s) with unit tests

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-cloud-aai/foca#31]
Check if there are differences between the Python modules in the following (sub)packages:

https://github.com/elixir-europe/WES-ELIXIR/tree/dev/cwl-wes/factories
https://github.com/elixir-europe/proWES/tree/master/pro_wes/factories
https://github.com/elixir-cloud-aai/proTES/tree/dev/pro_tes/factories

If there are differences, summarize, and discuss differences. If not, add modules to the archetype (adjusting import paths).

**Comment by uniqueg** [comment]
Updated label because I think this may potentially be not as straight-forward as some other modules, as I think we need to create and return app objects here which is harder to unit test and requires more changes in the target code base than just different import statements
