### ISSUE TITLE
Add Celery registration module

### ISSUE THREAD

**Issue by kushagra189** [elixir-cloud-aai/foca#41]
Check if there are differences between the Python modules in the following (sub)packages:

- https://github.com/elixir-cloud-aai/cwl-WES/tree/dev/cwl_wes/tasks
- https://github.com/elixir-europe/proWES/tree/master/pro_wes/tasks
- https://github.com/elixir-cloud-aai/proTES/tree/dev/pro_tes/tasks

If there are differences, summarize, and discuss differences. If not, add modules to the archetype (adjusting import paths).

**Comment by uniqueg** [comment]
For this, I think we can really only migrate the `register_celery.py` module. The background tasks are intrinsically service-dependent.

**Comment by kushagra189** [comment]
I was going through the `utils` part and I thing the `state` variable will be a hinderence. So for now I'll stick to the addition of `register_celery` part.

**Comment by uniqueg** [comment]
I think I will take care of this together with #31, based on PR #39. It's getting really tricky here

**Comment by uniqueg** [comment]
Actually, we can't use the `TaskMonitor` either, so what's left are just these calls:

```py
    if os.environ.get("WERKZEUG_RUN_MAIN") != 'true':
        celery_app = create_celery_app(app)
        logger.info('Celery task monitor registered.')
```
