### ISSUE TITLE
Set up automatic releases

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/foca#55]
Search for solution to handle automatic releases. Adapt CI pipeline accordingly.

**Comment by stikos** [comment]
Are we interested in semantic versioning? We're already using semantigc commit messages.
https://python-semantic-release.readthedocs.io/en/latest/

**Comment by uniqueg** [comment]
Additions to `.travis.yml` (possibly add to `deploy` section rather than `after_success`:
```
after_success:
- git config --global user.name "semantic-release (via TravisCI)"
- git config --global user.email "semantic-release@travis"
- semantic-release --verbosity=DEBUG publish
```

**Comment by uniqueg** [comment]
Remember to include Docker image names in automatic version bumps.
