### ISSUE TITLE
Package project

### ISSUE THREAD

**Issue by sarthak-sopho** [elixir-cloud-aai/foca#7]
Create the necessary files for uploading the project to PyPI (setup.py and possibly MANIFEST.in and setup.cfg)

**Comment by uniqueg** [comment]
You can have a look at [TEStribute's](https://github.com/elixir-europe/TEStribute) `setup.py` file for a more or less reasonable template. Of course some of the tags and classifiers need to be updated.

**Comment by sarthak-sopho** [comment]
@uniqueg 
I think we need to change the repo name. `archetype_flask_connexion`?
The style guide doesn't allow hyphens. Moreover, it also discourages the use of underscore. But we can stay with it also.

Reference: https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them

**Comment by uniqueg** [comment]
Good point about the name - let's find something else. Doesn't have to be a prescriptive name. Can you come up with one? Doesn't need to be English and doesn't necessarily need to mean anything

As for line lengths, you can write:
```
from package import (
    module_1,
    ...
   module_n,
)

**Comment by sarthak-sopho** [comment]
What about? 

- ga4gh
- ga4ghlib
-ga4ghArchetype
- elixiraii
- elixirArchetype

We can ask the community also if this also doesn't work. :P

**Comment by uniqueg** [comment]
I don't think it's really tied to either GA4GH or ELIXIR, it could totally be useful outside of these. How about fcoutils for Flask, Connexion and OpenAPI. Could be any other permutation of f, c and o also, or tools instead of utils. Or foca as in Flask, Connexion and OpenAPI archetype.

**Comment by sarthak-sopho** [comment]
`foca` sounds great actually. And it's unique also.

**Comment by uniqueg** [comment]
And short. So let's go with this

**Comment by uniqueg** [comment]
Closed by #22
