### ISSUE TITLE
Fix docstring formatting & set private members

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/foca#70]
Some docstrings are rendered in a slightly warped way in the [API docs](https://foca.readthedocs.io/en/latest/), mostly in cases where highlighting features are used (italics, bold, bullet points, refs to arguments/classes/methods/functions). Check the Sphinx docs and Google style reference to fix these.

Moreover, some helper functions/methods are shown that are better not exposed in the public API to keep it as easily accessible and focused as possible.

**Comment by kushagra189** [comment]
@uniqueg  should I go ahead with [this](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) recommended styling for docstrings?

**Comment by kushagra189** [comment]
@uniqueg can you elaborate what all methods are private? Also, the idea is to hide them and not document within the docs?

**Comment by uniqueg** [comment]
Never really saw that comment @kushagra189: I think we would want to "hide" everything that the users don't really need. So what **_do_** they need to know about:

- `foca.foca.foca()` function: to understand the main entry point into FOCA
- `foca.models.config` module: to understand how to write the config file
- `foca.utilities` subpackage: to see what useful functions they can import and reuse

I think everything else can be skipped from the API docs. As for how to skip them: I would probably not completely hide them, but change the table of contents in API docs so that only these are visible from the start. It would probably still be good to leave everything else in, perhaps under a link "complete API documentation" or so, as it is still useful for _FOCA_ developers (and sometimes app developers, too, if there are some bugs/issues).
