### ISSUE TITLE
Edit on github button do not work in API docs

### ISSUE THREAD

**Issue by sj00coder** [elixir-cloud-aai/foca#87]
in API DOCS [https://foca.readthedocs.io/en/latest/modules/foca.config.html](https://foca.readthedocs.io/en/latest/modules/foca.config.html) edit on github button  link to [https://github.com/elixir-cloud-aai/foca/blob/dev/docs/api/modules/foca.config.rst](https://github.com/elixir-cloud-aai/foca/blob/dev/docs/api/modules/foca.config.rst) which give a 404 page.
A working link is need to be link to the button

**Comment by uniqueg** [comment]
Thanks @sj00coder for pointing this out. It seems like it's a [common issue with Read the Docs](http://google.com/search?q=read+the+docs+edit+on+github+link+latest/broken&oq=read+the+docs+edit+on+github+link+broken&aqs=chrome..69i57j69i60l3.7469j0j7&sourceid=chrome&ie=UTF-8) and it may only be possible to deactivate the functionality globally. As it may still have some value (the links _do_ work for the [landing page](https://foca.readthedocs.io/en/latest/index.html)), I will close this issue and leave this as it is, at least for now.
