### ISSUE TITLE
CORS support should be optional

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/foca#90]
While I don't understand tne implications fully, I think [CORS][] should not be enabled for every microservice and thus should be made optional.

It's rather an easy fix but needs some changes all around (code, docstrings, possibly examples).

In principle, this is what needs to be done, as far as I can tell:
- [ ] A config parameter `enable_cors` should be added to the `SecurityConfig` model (set default to `True`) in `foca/models/config.py`; update docstring accordingly, including example and, if necessary, dependent examples (search file for any mentions of `SecurityConfig`)
- [ ] In the main FOCA file (`foca/foca.py`), the value of the config parameter should be read to decide whether to call `enable_cors()` in line 49 (i.e., add an `if ...` around that call and the log message, maybe add another log message to say that CORS is disabled in the `else ...` block)
- [ ] Check if any documentation needs to be updated

**Comment by vipulchhabra99** [comment]
Can you please assign me this issue? @uniqueg
