### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/foca#95]
Currently, all dependencies are listed in `requirements.txt`. However, many of these are not required for actual FOCA functionality, but rather for developing FOCA (e.g., to run tests, calculate and publish code coverage, for linting the code, building/releasing packages etc.). For end users of FOCA, all of these packages are possibly not needed and they simply bloat the FOCA Docker image and derived app images.

To clean up dependencies, first remove any packages from `requirements.txt` that are used for _building and distributing_ packages (currently only `twine`) and add them to the `setup_requires` section inside `setup.py`. Then move all other packages that are not required for FOCA functionality (i.e., packages only used for testing, linting etc) into a new file `requirements_dev.txt`. To make sure the CI environment has all packages it needs to run tests, add an `install` section (see, e.g., [here](https://docs.travis-ci.com/user/languages/python/#specifying-python-versions)) to the Travis CI config and add the commands to first install the packages in `requirements.txt` (Travis automatically does that if no `installs` section is provided and the `language` is set to `python`, but I think it will not do so if `install` is overridden), then to install the development packages inside `requirements_dev.txt`. While you are at it, you can add `python-semantic-release` to `requirements_dev.txt` as well and then remove the line `pip install python-semantic-release==7.15.0` from the Travis config (as it will then be installed along with other packages in the development dependencies file). Lastly, check whether any changes to the documentation (`README.md`, `examples/petstore/README.md`) are required as a consequence of this change (there may _not_ be, but it's important to verify).

> Note: I think that similarly to Travis, Read the Docs (used for building API docs) by default will install packages from `requirements.txt`, but not any custom environment files, so if it needs any of these packages, doc building may fail. If that is the case (triggering the CI by pushing, e.g., a feature branch will tell you), please let me know and I will figure out the necessary changes in the Read the Docs configuration.

**Comment by jain-rishabh-21** [comment]
Hi, Can you assign me this issue. I will figure things out and will start working on it!

**Comment by anuragxxd** [comment]
@jain-rishabh-21 I can work on this if you are not working on this.

**Comment by jain-rishabh-21** [comment]
Hey anurag, I got involved in some things, will raise a PR soon! 😀
